apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nks-test
  name: nks-test
  namespace: test-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2 ## argoCD 최대 갯수 제한
  selector:
    matchLabels:
      app: nks-test
  template:
    metadata:
      labels:
        app: nks-test
    spec:
      containers:
      - image: test-nks-container-registry.kr.ncr.ntruss.com/nks-test:v1.0.0
        name: nks-test:v1.0.0
        env:
        - name: SERVER_PORT ## env파일 생성시 source에 있는 환경 변수 확인 하여 생성
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: nks-test
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: db_url
        - name: DB_POOL_SIZE
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: db_pool_size        
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: db_pass
        - name: JPA_GENERATE_DDL
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: jpa_generate_ddl
        - name: JPA_DDL_AUTO
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: jpa_ddl_auto
        - name: DB_DRIVER_CLASS_NAME
          valueFrom:
            secretKeyRef:
              name: nks-test
              key: db_driver_class_name
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: nks-test
  namespace: test-ns
spec:
  selector:
    app: nks-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
