# Default values for emoldinochart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 680723068970.dkr.ecr.us-east-2.amazonaws.com/test-demo
  tag: 24bd0509c1d3a84947618aebdc2aa5053f52394e
  pullPolicy: IfNotPresent

configs:
  configName: demo-application-properties
  volumeMountsVar:
    name: application-properties
    mountPathVar: /emoldino/config 
  restartPolicy: Always
    

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort 
  port: 8080
  nodePort: 30182
  targetPort: 80
  selector:
    app: emoldino

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balancer-name: 'ohio-k8s-alb'
    alb.ingress.kubernetes.io/group-order: '3'

  hosts:
    - host: demo.test.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              port:
                number: 80
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90

nodeSelector: 
  app: demo
tolerations: []
affinity: {}
