apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: emoldino=680723068970.dkr.ecr.us-east-2.amazonaws.com/emoldino-demo
    argocd-image-updater.argoproj.io/emoldino.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/emoldino.update-strategy: latest
    argocd-image-updater.argoproj.io/emoldino.pull-secret: secret:argocd/aws-ecr-creds#creds

    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: master

spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: image.repository
          value: 680723068970.dkr.ecr.us-east-2.amazonaws.com/emoldino
          forceString: true
        - name: image.tag
          value: 24bd0509c1d3a84947618aebdc2aa5053f52394e
          forceString: true
      valueFiles:
        - ohio-demo-values.yaml
    path: helm/emoldinochart
    repoURL: https://github.com/myhr123/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
